/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Sanctuary = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSanctuary' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'getAllSanctuaries' : IDL.Func([], [IDL.Vec(Sanctuary)], ['query']),
  'getDaySanctuaries' : IDL.Func([Time], [IDL.Vec(Sanctuary)], ['query']),
  'getSanctuariesByMonth' : IDL.Func([Time], [IDL.Vec(Sanctuary)], ['query']),
  'getSanctuariesByYear' : IDL.Func([Time], [IDL.Vec(Sanctuary)], ['query']),
  'getSanctuary' : IDL.Func([IDL.Text], [Sanctuary], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Sanctuary = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addSanctuary' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'getAllSanctuaries' : IDL.Func([], [IDL.Vec(Sanctuary)], ['query']),
    'getDaySanctuaries' : IDL.Func([Time], [IDL.Vec(Sanctuary)], ['query']),
    'getSanctuariesByMonth' : IDL.Func([Time], [IDL.Vec(Sanctuary)], ['query']),
    'getSanctuariesByYear' : IDL.Func([Time], [IDL.Vec(Sanctuary)], ['query']),
    'getSanctuary' : IDL.Func([IDL.Text], [Sanctuary], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };